### ISSUE TITLE
use https://github.com/felixfbecker/node-sql-template-strings for the sql tag stuff ?

### ISSUE THREAD

**Issue by abenhamdine** [charmander/pg-auto#1]
Hi charmander,

If you don't already know it, you could be interested by https://github.com/felixfbecker/node-sql-template-strings 

We use it since one year in production, it's ok.

**Comment by charmander** [comment]
Thanks for the link @abenhamdine – I wasn’t aware of that package. It doesn’t look quite strict enough to  replace the type here, though, as its `append` will also accept a simple string value and convert it to query text.
